spring:
  application:
    name: ms-notification

  data:
    mongodb:
      host: localhost
      port: 27017
      database: notifications-db
      auto-index-creation: false

  cloud:
    stream:
      default-binder: kafka

      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          auto-create-topics: true

      bindings:
        processCreditDecision-in-0:
          destination: credit-decided
          group: notifications-group
          content-type: application/json

server:
  port: 8084


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

# Informações da aplicação (aparece no /actuator/info)
info:
  app:
    name: ${spring.application.name}
    description: Credit Analysis System
    version: 1.0.0