spring:
  application:
    name: camunda-starter

  # Kafka (Spring Cloud Stream)
  cloud:
    stream:
      default-binder: kafka

      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          auto-create-topics: true
          required-acks: 1

      bindings:
        # Consumer: escuta credit-requested
        processCreditRequest-in-0:
          destination: credit-requested
          group: camunda-starter-group
          content-type: application/json

        # Producer: publica credit-decided
        creditDecided-out-0:
          destination: credit-decided
          content-type: application/json

server:
  port: 8085

# Camunda External Task Client
camunda:
  bpm:
    client:
      base-url: ${CAMUNDA_REST_URL:http://localhost:8080/engine-rest}
      lock-duration: 60000
      async-response-timeout: 10000
      worker-id: camunda-starter-worker
      max-tasks: 10
