spring:
  application:
    name: camunda-starter

  # Kafka (Spring Cloud Stream)
  cloud:
    function:
      definition: processCreditRequest;reprocessDlq
    stream:
      default-binder: kafka

      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          auto-create-topics: true
          required-acks: 1
        bindings:
          processCreditRequest-in-0: #Configuração da DLQ
            enable-dlq: true
            dlq-name: credit-requested-dlq
            dlq-header-context-retention-action: annotate_and_discard

      bindings:
        # Consumer: escuta credit-requested
        processCreditRequest-in-0:
          destination: credit-requested
          group: camunda-starter-group
          content-type: application/json
          consumer:
            max-attempts: 3 # Tenta 1 original + 2 retentativas
            back-off-initial-interval: 2000 # Espera 2 seg na primeira falha
            back-off-multiplier: 2.0        # Dobra o tempo (2s -> 4s)

        # Producer: publica credit-decided
        creditDecided-out-0:
          destination: credit-decided
          content-type: application/json

        #Producer: reprocessamento
        reprocess-out-0:
          destination: credit-requested
          content-type: application/json

        # Consumer de reprocessamento
        reprocessDlq-in-0:
          destination: credit-requested-dlq
          group: dlq-reprocessor-group

server:
  port: 8085

# Camunda External Task Client
camunda:
  bpm:
    client:
      base-url: ${CAMUNDA_REST_URL:http://localhost:8080/engine-rest}
      lock-duration: 60000
      async-response-timeout: 10000
      worker-id: camunda-starter-worker
      max-tasks: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

# Informações da aplicação (aparece no /actuator/info)
info:
  app:
    name: ${spring.application.name}
    description: Credit Analysis System
    version: 1.0.0
