spring:
  application:
    name: ms-scoring

  # Configuração do MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/credit-db
      auto-index-creation: true

    # Configuração do Redis (Cache de Score)
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    stream:
      # Define Kafka como binder padrão
      default-binder: kafka

      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          auto-create-topics: true
          required-acks: 1

      bindings:
        # Consumer: Escuta o evento de solicitação de crédito
        processCreditRequest-in-0:
          destination: credit-requested  # O mesmo tópico que o ms-credit publica
          group: scoring-group           # Grupo de consumo
          content-type: application/json

server:
  port: 8082
